#include <stdio.h>
#include "runner.h"

/* Shared counters — all test files reference these via extern */
int g_pass     = 0;
int g_fail     = 0;
int g_test_fail = 0;

void run_parse_tests(void);
void run_rate_tests(void);
void run_state_tests(void);
void run_scenario_tests(void);
void run_conns_tests(void);
void run_wifi_tests(void);
void run_packets_tests(void);
void run_procs_tests(void);
void run_bw_tests(void);
void run_dns_tests(void);
void run_stats_tests(void);
void run_probe_tests(void);
void run_oui_tests(void);
void run_services_tests(void);
void run_arp_tests(void);
void run_pcap_write_tests(void);
void run_iface_graph_tests(void);
void run_geo_tests(void);
void run_dhcp_tests(void);
void run_rtt_tests(void);
void run_tree_tests(void);
void run_scan_tests(void);
void run_dns_snoop_tests(void);
void run_sni_snoop_tests(void);
void run_mdns_snoop_tests(void);
void run_http_snoop_tests(void);
void run_nbns_snoop_tests(void);
void run_dhcp_snoop_tests(void);
void run_quic_snoop_tests(void);
void run_ssdp_snoop_tests(void);
void run_beacon_snoop_tests(void);
void run_deauth_snoop_tests(void);
void run_http_log_tests(void);
void run_tls_log_tests(void);
void run_quic_log_tests(void);
void run_dns_log_tests(void);
void run_ntp_log_tests(void);
void run_icmp_log_tests(void);
void run_threat_intel_tests(void);
void run_alerts_tests(void);
void run_md5_tests(void);
void run_devices_tests(void);
void run_beacon_detect_tests(void);
void run_jsonl_tests(void);
void run_filter_tests(void);
void run_alert_pcap_tests(void);
void run_ip_owner_tests(void);
void run_dashboard_tests(void);
void run_ip_color_tests(void);
void run_top_hosts_tests(void);
void run_host_cache_tests(void);
void run_probe_pnl_tests(void);
void run_eapol_log_tests(void);
void run_seqnum_track_tests(void);
void run_assoc_track_tests(void);
void run_channel_tests(void);
void run_dga_tests(void);
void run_data_socket_tests(void);
void run_osi_tests(void);

int main(void) {
    printf("sloth test suite\n");
    printf("===============\n");

    run_parse_tests();
    run_rate_tests();
    run_state_tests();
    run_scenario_tests();
    run_conns_tests();
    run_wifi_tests();
    run_packets_tests();
    run_procs_tests();
    run_bw_tests();
    run_dns_tests();
    run_stats_tests();
    run_probe_tests();
    run_oui_tests();
    run_services_tests();
    run_arp_tests();
    run_pcap_write_tests();
    run_iface_graph_tests();
    run_geo_tests();
    run_dhcp_tests();
    run_rtt_tests();
    run_tree_tests();
    run_scan_tests();
    run_dns_snoop_tests();
    run_sni_snoop_tests();
    run_mdns_snoop_tests();
    run_http_snoop_tests();
    run_nbns_snoop_tests();
    run_dhcp_snoop_tests();
    run_quic_snoop_tests();
    run_ssdp_snoop_tests();
    run_beacon_snoop_tests();
    run_deauth_snoop_tests();
    run_http_log_tests();
    run_tls_log_tests();
    run_quic_log_tests();
    run_dns_log_tests();
    run_ntp_log_tests();
    run_icmp_log_tests();
    run_threat_intel_tests();
    run_alerts_tests();
    run_md5_tests();
    run_devices_tests();
    run_beacon_detect_tests();
    run_jsonl_tests();
    run_filter_tests();
    run_alert_pcap_tests();
    run_ip_owner_tests();
    run_dashboard_tests();
    run_ip_color_tests();
    run_top_hosts_tests();
    run_host_cache_tests();
    run_probe_pnl_tests();
    run_eapol_log_tests();
    run_seqnum_track_tests();
    run_assoc_track_tests();
    run_channel_tests();
    run_dga_tests();
    run_data_socket_tests();
    run_osi_tests();

    RUNNER_SUMMARY();
    return g_fail > 0 ? 1 : 0;
}
