/* Approved-inventory trust anchor — issue #89 slice 2.
 *
 * Slice 1 removed three things the evil-twin rules treated as proof of
 * ownership — a matching vendor OUI, an 802.11k neighbour report, and
 * RSSI — because all three are facts an attacker writes into a frame.
 * That left the detector honest but anchorless: it could say "these two
 * radios disagree" and never "that one is not mine".
 *
 * This is the anchor. It is the operator's own statement of which
 * BSSIDs are approved for which SSID, supplied out-of-band as a file,
 * and it is the only trust input in the twin family that does not come
 * off the air. Everything observed stays weighted context; only this
 * can exonerate a pair outright, and only because a human wrote it.
 *
 * ── The file ──────────────────────────────────────────────
 *
 *   { "version": "2026-09-24.1",
 *     "site": "hq-3f",
 *     "networks": [
 *       { "ssid": "CorpWiFi",
 *         "security_profile": "wpa2-enterprise",
 *         "bssids": ["aa:bb:cc:00:11:22", "aa:bb:cc:00:11:23"] } ] }
 *
 * `version` and `site` are optional; `networks` is required. Unknown
 * keys are ignored (forward-compatible, same rule src/updater.c applies
 * to the release manifest) but still parsed, so junk in a field sloth
 * does not read is still a malformed file.
 *
 * ── Parsed as hostile data ────────────────────────────────
 *
 * This is operator-supplied DATA, not trusted input: a file on a sensor
 * that several people edit, or one generated by a script against a
 * controller API. Every failure mode below is rejected with a message
 * naming what was wrong, and **the load is all-or-nothing** — a file
 * that half-parses loads nothing. A partial inventory is the worst
 * outcome available: the operator believes their APs are approved while
 * the dropped half of the list alerts as rogue, or worse, a dropped
 * rogue silently reads as unremarkable.
 *
 * MISSION §2 is untouched: this is a local file read at startup and
 * never re-read, never fetched, never written. There is no reload path
 * on purpose — a reload would be an inbound-configuration surface,
 * which MISSION §4 puts out of scope, and it would let the anchor
 * change underneath a live incident.
 *
 * ── Identity is the content hash ──────────────────────────
 *
 * `inventory_hash()` is derived from the file's bytes, and it is
 * stamped into every alert and export that consulted the inventory, so
 * a finding can be traced to the exact file that produced it. The
 * human-readable `version` string rides along as a label only: nothing
 * stops two different files from claiming "2026-09-24.1". */

#ifndef SLOTH_INVENTORY_H
#define SLOTH_INVENTORY_H

#include <stddef.h>
#include <stdint.h>

/* Bounded like every other table in the tree. A site with more APs than
 * this wants a controller export feeding a generated file, and the
 * generator can split it per sensor. Exceeding a cap is an error, never
 * a truncation — see the all-or-nothing note above. */
#define INV_MAX_NETWORKS    64
#define INV_MAX_BSSIDS     512    /* total across all networks */
#define INV_SSID_LEN        33    /* 32 octets on the air + NUL */
#define INV_PROFILE_LEN     24
#define INV_SITE_LEN        33
#define INV_VERSION_LEN     33
#define INV_HASH_LEN        17    /* 16 hex chars + NUL */
#define INV_ERR_MAX        256
#define INV_FILE_MAX    (256 * 1024)
#define INV_MAX_DEPTH        8    /* nesting cap — bounds the recursion */

/* What the inventory says about one (SSID, BSSID) sighting.
 *
 * The three-way split matters: "the inventory does not mention this
 * SSID" is not the same fact as "this BSSID is approved", and treating
 * silence as approval is how a trust anchor turns into a blind spot. */
typedef enum {
    INV_NO_INVENTORY = 0,  /* no file loaded, or this SSID is not listed */
    INV_APPROVED,          /* SSID listed and this BSSID is in its set */
    INV_MISMATCH,          /* SSID listed and this BSSID is NOT in its set */
} inv_verdict_t;

/* Read and validate `path`. Returns 1 on success, 0 on any failure with
 * a one-line reason in `err` (never a partial load — a failed call
 * leaves the previous state untouched, and at startup that is empty).
 * `err` may be NULL. */
int  inventory_load(const char *path, char *err, size_t errsz);

/* Drop everything, including a --site set by flag. */
void inventory_clear(void);

/* 1 once a file has loaded successfully. `--site` alone does not make
 * an inventory: a label is not an approved-BSSID list. */
int  inventory_loaded(void);

int  inventory_network_count(void);
int  inventory_bssid_count(void);

/* Content hash of the loaded file, "" when none. 16 hex characters of
 * SHA-256 over the raw bytes — an identity label for a local file in an
 * alert line, not a security boundary, and 64 characters of hex on
 * every twin alert would be noise the operator has to read past. */
const char *inventory_hash(void);

/* The file's `version` string, "" when absent. A label. */
const char *inventory_version(void);

/* The operator's name for where this sensor is, "" when unset.
 *
 * CONFIGURATION ONLY (Captain's decision, 2026-09-25). It comes from
 * --site or the file's `site` field and from nothing else. It is never
 * derived from the uplink association, an observed SSID, or any
 * captured frame: that would be a trust anchor built on unauthenticated
 * RF, which is the bug class #89 exists to remove — and a site that
 * re-keys on every roam would fragment one physical impersonator into
 * several incidents, because `site` is part of the canonical pair key.
 * Unset means unset; the key then carries an empty site and stays
 * stable. There is no provenance field because there is no second
 * source. */
const char *inventory_site(void);

/* Set the site from --site. Returns 1, or 0 with a diagnostic on stderr
 * for an empty, over-long, non-printable or ':'-bearing label (':'
 * separates fields in the canonical pair key). Order-independent: the
 * flag wins over the file's `site` whichever is applied first. */
int  inventory_set_site(const char *site);

/* The trust question, for one observed (SSID, BSSID).
 *
 * ── Flag merge (#52) ──────────────────────────────────────
 *
 * `--my-ssid` / `--my-bssid` keep working exactly as they did and are
 * **unioned** with the file, never intersected: a BSSID designated by
 * --my-bssid counts as approved for any SSID the inventory lists. Both
 * are the same kind of statement — a human asserting ownership — so
 * there is no ground for preferring one over the other, and
 * intersecting would mean that adding a flag could manufacture a rogue
 * out of the operator's own AP. Union is the safe direction for an
 * anchor whose failure mode is alerting on your own infrastructure.
 *
 * An SSID named by --my-ssid but absent from the file is
 * INV_NO_INVENTORY: the flag says the network is ours, it does not
 * enumerate which radios are allowed to serve it, so no mismatch can be
 * computed from it. */
inv_verdict_t inventory_verdict(const char *ssid, const uint8_t bssid[6]);

/* The operator's declared security profile for `ssid`, "" when the SSID
 * is not listed or the entry omitted it.
 *
 * Carried and displayed, deliberately NOT matched against the observed
 * `enc` string. Doing that needs a normalisation table between operator
 * vocabulary ("wpa2-enterprise") and sloth's beacon-derived ciphers
 * ("WPA2"), and a wrong entry in that table alerts on the operator's
 * own APs — the exact failure this anchor exists to prevent. It is a
 * label for the human reading the finding until that mapping is
 * specified. */
const char *inventory_profile_for_ssid(const char *ssid);

#endif /* SLOTH_INVENTORY_H */
